# Generated by Django 5.2.1 on 2025-05-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('oab', models.CharField(max_length=20)),
                ('data_admissao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvogadoCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=100)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.advogado')),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('advogados', models.ManyToManyField(through='upload.AdvogadoCausa', to='upload.advogado')),
            ],
        ),
        migrations.AddField(
            model_name='advogadocausa',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.causa'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='escritorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogados', to='upload.escritorio'),
        ),
        migrations.AlterUniqueTogether(
            name='advogadocausa',
            unique_together={('advogado', 'causa')},
        ),
    ]
