# Generated by Django 5.2.1 on 2025-05-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('oab', models.CharField(max_length=20)),
                ('data_admissao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cnpj', models.CharField(max_length=18)),
                ('oab', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('qtd_funcionarios', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvogadoCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=100)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.advogado')),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('arquivo_peticao', models.FileField(blank=True, null=True, upload_to='peticoes/')),
                ('advogados', models.ManyToManyField(through='upload.AdvogadoCausa', to='upload.advogado')),
            ],
        ),
        migrations.AddField(
            model_name='advogadocausa',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.causa'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='upload.causa')),
            ],
        ),
        migrations.AddField(
            model_name='advogado',
            name='escritorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogados', to='upload.escritorio'),
        ),
        migrations.AlterUniqueTogether(
            name='advogadocausa',
            unique_together={('advogado', 'causa')},
        ),
    ]
