# Generated by Django 5.2.1 on 2025-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escritorio',
            name='senha',
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='numero',
            field=models.CharField(default='S/N', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='qtd_funcionarios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
