# Generated by Django 5.2.1 on 2025-05-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='arquivo_peticao',
            field=models.FileField(blank=True, null=True, upload_to='peticoes/'),
        ),
        migrations.AddField(
            model_name='causa',
            name='dados_extraidos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='causa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='upload.causa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
