# Generated by Django 5.2.1 on 2025-05-19 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_escritorio_senha_alter_escritorio_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='escritorio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='peticoes', to='upload.escritorio'),
            preserve_default=False,
        ),
    ]
